GeekStreamProject/src/GeekStreamProject.App/Controllers/ArticleReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GeekStreamProject.Core.Abstractions;
using GeekStreamProject.Core.Abstractions.Services;
using GeekStreamProject.Core.ViewModels;
using GeekStreamProject.Core.ViewModels.Article;
using GeekStreamProject.Core.Shared.Entities;
using GeekStreamProject.Core.ViewModels.Comment;
using GeekStreamProject.Core.ViewModels.Review;
using GeekStreamProject.ENums.ENums;
using MailKit.Net.Smtp;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace GeekStreamProject.App.Controllers
{
    public class ArticleReviewsController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ICategoryService _categoryService;
        private readonly ICommentService _commentService;
        private readonly IArticleReviewService _articleReviewService;

        public ArticleReviewsController(IArticleService articleService, ICategoryService categoryService,
            UserManager<ApplicationUser> userManager, ICommentService commentService, IArticleReviewService articleReviewService)
        {
            _articleService = articleService;
            _categoryService = categoryService;
            _userManager = userManager;
            _commentService = commentService;
            _articleReviewService = articleReviewService;
        }

        
        [HttpGet]
        public async Task<IActionResult> ReviewArticle(int id)
        {
            var reviewArticleViewModel = await _articleReviewService.GetReviewArticle(id);
            if (reviewArticleViewModel == null)
            {
                return NotFound();
            }
            
            return View(reviewArticleViewModel);
        }

        [HttpGet]
        public IActionResult ApproveArticle()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ApproveArticle(CreateApproveViewModel model, int articleReviewId)
        {
            await  _articleReviewService.ApproveArticle(model);
            var articleByReview = await _articleService.GetArticleByReview(articleReviewId);
            if (articleByReview is null)
            {
                return NotFound();
            }
            return RedirectToAction("ReviewArticle", new { id = articleByReview.Id });
        }

        [HttpGet]
        public async Task<IActionResult> UnApprove(int approveId, int articleReviewId)
        {
            await _articleReviewService.UnApprove(approveId);
            var articleByReview = await _articleService.GetArticleByReview(articleReviewId);
            if (articleByReview is null)
            {
                return NotFound();
            }
            return RedirectToAction("ReviewArticle", new { id = articleByReview.Id });
        }
    }
}

GeekStreamProject/src/GeekStreamProject.App/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GeekStreamProject.Core.Abstractions;
using GeekStreamProject.Core.Abstractions.Services;
using GeekStreamProject.Core.ViewModels.Chat;
using Microsoft.AspNetCore.Mvc;

namespace GeekStreamProject.App.Controllers
{
    public class ChatController : Controller
    {
        private readonly IChatService _chatService;

        public ChatController(IChatService chatService)
        {
            _chatService = chatService;
        }

        public IActionResult _LayoutChat()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Chat()
        {
            IEnumerable<MessageViewModel> chatMessages = await _chatService.GetLatestMessages();

            if (chatMessages == null)
            {
                return NotFound();
            }

            return View(chatMessages);
        }
    }
}

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/DefaultNavBar.cshtml
@using AutoMapper.Configuration.Annotations
@{
    string _state = Guid.NewGuid().ToString();
}

<nav class="navbar navbar-light bg-white">
    <div class="container-fluid align-content-center nav-font">
        <div class="d-flex gap-3 py-2">
            <div>
                <a class="navbar-brand" asp-controller="Articles" asp-action="Articles">
                    <img src="~/ImageStorage/Logo/GeekStreamProject_Logo.png" width="40" height="40" alt="">
                </a>
            </div>
            <div>
                <ul class="nav gap-3 align-content-center">
                    <li class="nav-item">
                        <a class="nav-link px-0" asp-controller="Articles" asp-action="Articles">Статьи</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-0" asp-controller="Chat" asp-action="Chat">Дискуссии</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-0" asp-controller="Categories" asp-action="Categories">Категории</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-0" asp-controller="Account" asp-action="Authors">Авторы</a>
                    </li>
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="btn btn-purple nav-font" asp-controller="Account" asp-action="ForAnonymUser">Написать статью</a>
                        </li>
                    }
                    else if (User.Identity.IsAuthenticated && User.IsInRole("Moderator"))
                    {
                        <li class="nav-item">
                            <a class="btn btn-purple nav-font" asp-controller="Account" asp-action="ForAnonymUser">Написать статью</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="btn btn-purple nav-font" asp-controller="Articles" asp-action="Create">Написать статью</a>
                        </li>
                    }

                    
                </ul>
            </div>
            <form class="d-flex gap-3 align-content-center">
                <input class="form-control mr-sm-2 nav-border nav-search" type="search" placeholder="Найти статью" aria-label="Найти статью">
                <button class="btn btn-outline-dark nav-border nav-link nav-font" type="submit">Поиск</button>
            </form>

        </div>
        <div>
            <div class="d-flex gap-3">
                <div>
                    <a class="btn btn-outline-dark nav-border nav-font nav-link" asp-controller="Account" asp-action="Login">Войти</a>
                </div>
                <div>
                    <a class="btn btn-outline-dark nav-border nav-font nav-link" href=@Url.Action("Register","Account",new { state = _state })>Регистрация</a>
                </div>
            </div>
        </div>
    </div>
</nav>

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/ExtendedNavBar.cshtml
@using AutoMapper.Configuration.Annotations
@using System.Security.Claims;
@using GeekStreamProject.Core.Shared.Abstractions.DataAccess;
@using Microsoft.AspNetCore.Http;

@{
    var avatarUrl = User.Claims
        .Where(c => c.Type == "avatarUrl")
        .Select(c => c.Value).FirstOrDefault(); }

<nav class="navbar navbar-light bg-white">
    <div class="container-fluid align-content-center nav-font">
        <div class="d-flex gap-3 py-2">
            <div>
                <a class="navbar-brand" asp-controller="Articles" asp-action="Articles">
                    <img src="~/ImageStorage/Logo/GeekStreamProject_Logo.png" width="40" height="40" alt="">
                </a>
            </div>
            <div>
                <ul class="nav gap-3 align-content-center">
                    <li class="nav-item">
                        <a class="nav-link px-0" asp-controller="Articles" asp-action="Articles">Статьи</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-0" asp-controller="Chat" asp-action="Chat">Дискуссии</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-0" asp-controller="Categories" asp-action="Categories">Категории</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-0" asp-controller="Account" asp-action="Authors">Авторы</a>
                    </li>
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="btn btn-purple nav-font" asp-controller="Account" asp-action="ForAnonymUser">Написать статью</a>
                        </li>
                    }
                    else if (User.Identity.IsAuthenticated && User.IsInRole("Moderator"))
                    {
                        <li class="nav-item">
                            <a class="btn btn-purple nav-font" asp-controller="Account" asp-action="ForModeratorUser">Написать статью</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="btn btn-purple nav-font" asp-controller="Articles" asp-action="Create">Написать статью</a>
                        </li>
                    }
                </ul>
            </div>
            <form class="d-flex gap-3 align-content-center">
                <input class="form-control mr-sm-2 nav-border nav-search" type="search" placeholder="Найти статью" aria-label="Найти статью">
                <button class="btn btn-outline-dark nav-border nav-link nav-font" type="submit">Поиск</button>
            </form>

        </div>
        <div>
            <div>
                <ul class="nav gap-3 align-content-center">
                    <li class="nav-item">
                        <a class="nav-link nav-user px-0" asp-controller="Account" asp-action="UserProfile" asp-route-userName="@User.Identity.Name">
                            Hello, @User.Identity.Name
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="px-0" asp-controller="Account" asp-action="UserProfile" asp-route-userName="@User.Identity.Name">
                            <img src="~/@avatarUrl" class="nav-image" alt="" />
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-outline-dark nav-border nav-link nav-font" asp-controller="Account" asp-action="UserSignOut" asp-route-id="@User.Identity.Name" >Выйти</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/_ArticleList.cshtml
@using Microsoft.AspNetCore.Identity;
@using System.Security.Claims;
@using GeekStreamProject.Core.Shared.Entities;

@model IEnumerable<GeekStreamProject.Core.ViewModels.Article.ArticleViewModel>

<div class="d-flex bd-highlight flex-column gap-sm-4">
    @foreach (var article in Model ?? Enumerable.Empty<ArticleViewModel>())
    {
    <div class="d-flex bd-highlight flex-column article-box bg-white gap-3 p-4">
        <div class="d-flex bd-highlight justify-content-between align-items-center">
            <div class="d-flex bd-highlight gap-2">
                <a asp-action="ArticlesByCategory" asp-controller="Categories" asp-route-id="@article.CategoryId"
                   class="d-flex bd-highlight gap-2 text-decoration-none">
                    <div class="image-list">
                        <img class="img-fluid" src="~/@article.CategoryImagePath" />
                    </div>
                    <span class="font-login color-category">
                        @article.CategoryName
                    </span>
                </a>
                <span class="color-datecreation font-content-create">@article.DateOfCreation</span>
            </div>
            <div class="d-flex bd-highlight gap-2 align-items-center">
                <a asp-controller="Account" asp-action="UserProfile" asp-route-userName="@article.AuthorName"
                   class="d-flex bd-highlight gap-2 text-decoration-none">
                    <div class="">
                        <img class="image-list" src="~/@article.AuthorAvatarPath" />
                    </div>
                    <span class="font-login color-name">
                        @article.AuthorName
                    </span>
                </a>
            </div>
        </div>
        <div class="bd-highlight">
            <a asp-controller="Articles" asp-action="DetailArticle" asp-route-id="@article.Id" class="text-decoration-none" id="title-list-article"><span>@article.Title</span></a>
        </div>
        <div class="bd-highlight box">
            <img src="~/@article.ImagePath" class="mx-auto"  >
        </div>
        <div class="bd-highlight font-article-content-list">
            <span>@article.Description</span>
</div>
        <div class="d-flex bd-highlight justify-content-between">
            <div class="d-flex gap-2 bd-highlight">
                <div class="bd-highlight">
                    <img src="~/ImageStorage/Default/Comment.png" />
                </div>
                <div class="bd-highlight font-content" style="color: #828282 !important; font-size: 20px">
                    @article.CommentCount
                </div>
            </div>
            <div class="d-flex gap-3 bd-highlight">
                @if (User.Identity.IsAuthenticated && User.FindFirstValue(ClaimTypes.Role) == "Admin")
                {
                    <div class="bd-highlight">
                        <a asp-controller="Articles" asp-action="Delete" asp-route-id="@article.Id" asp-route-userName="@article.AuthorName" class="text-decoration-none">Удалить</a>
                    </div>
                }
                <div class="bd-highlight">
                    <a  asp-action="ChangeRating" asp-controller="Articles" asp-route-id="@article.Id" asp-route-delta="@(-1)"><img class="rating-down" src="~/ImageStorage/Default/DownVector.png" /></a>
                </div>
                <div class="bd-highlight font-content-create" style="color: #219653 !important; font-size: 20px">
                    @article.Rating
                </div>
                <div class="bd-highlight">
                    <a asp-action="ChangeRating" asp-controller="Articles" asp-route-id="@article.Id" asp-route-delta="@(1)"><img class="rating-up" src="~/ImageStorage/Default/UpVector.png" /></a>
                </div>
            </div>
        </div>

    </div>

    }
</div>

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/_AuthorList.cshtml
@model IEnumerable<GeekStreamProject.Core.ViewModels.User.AuthorViewModel>


<div class="d-flex bd-highligh flex-column gap-sm-4">
    @foreach (var author in Model ?? Enumerable.Empty<AuthorViewModel>())
    {
        <div class="d-flex bd-highligh flex-column gap-3 bg-white article-box p-4">
            <div class="bd-highligh d-flex gap-3 align-content-center justify-content-between">
                <div class="d-flex bd-highligh gap-4 align-items-center ">
                    <a asp-controller="Account" asp-action="UserProfile" asp-route-userName="@author.UserName"
                       class="d-flex bd-highlight align-items-center  gap-2 text-decoration-none">
                        <div class="">
                            <img class="image-authors" src="~/@author.AvatarPath" />
                        </div>
                        <span class="font-header color-name">
                            @author.FirstName  @author.LastName ( @author.UserName )
                        </span>
                    </a>
                    <div class="d-flex bd-highlight gap-3 align-items-center">
                        <span class="font-inter-500">
                            Кол-во статей: @author.CountArticle
                        </span>
                    </div>
                    
                </div>
                <div class="d-flex gap-3 align-content-center bd-highlight">
                    <div class="bd-highlight">
                        <img src="~/ImageStorage/Default/DownVector.png"/>
                    </div>
                    <div class="bd-highlight font-content-create" style="color: #219653 !important; font-size: 20px">
                        @author.Rating
                    </div>
                    <div class="bd-highlight">
                        <img src="~/ImageStorage/Default/UpVector.png"/>
                    </div>
                </div>
            </div>
            @if (author.articleViewModel != null)
            {
                <div class="d-flex bd-highligh align-items-center gap-3">
                    <a asp-controller="Articles" asp-action="DetailArticle" asp-route-id="@author.articleViewModel.Id"
                       class="text-decoration-none"><span class="font-content">@author.articleViewModel.Title</span></a>
                    <span class="color-datecreation font-content-create">@author.articleViewModel.DateOfCreation</span>
                </div>
            }
            
        </div>
    }
</div>

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/_CategoryList.cshtml
@model IEnumerable<GeekStreamProject.Core.ViewModels.Category.CategoryViewModel>
<input type="hidden" value=@using System.Security.Claims />
@foreach (var category in Model ?? Enumerable.Empty<CategoryViewModel>())
{
<div class="row mb-4">
    <div class="bg-white p-0 border-card">
        <div class="bd-highlight category">
            <img src="~/@category.CoverPath" class="mx-auto">
        </div>
        <div class="px-5 py-3">
            <div class="d-flex justify-content-between">
                <div class="d-flex gap-2 align-items-center">
                    <div class="rounded-2 overflow-hidden" style="width: 2rem; height: 2rem;">
                        <img class="img-fluid w-100 h-100 d-block" src="@category.ImagePath" />
                    </div>
                    <a asp-action="ArticlesByCategory" asp-controller="Categories" asp-route-id="@category.Id" class="text-decoration-none">
                        <h3 class="fw-bold" style="color: #4F4F4F">@category.Name</h3>
                    </a>
                    <div class="font-article-content-list">
                        <span>Публикаций: @category.CountArticles</span>
                    </div>
                </div>
            @if (User.Identity.IsAuthenticated && User.FindFirstValue(ClaimTypes.Role) == "Admin")
            {
                <div>
                    <a class="text-decoration-none" asp-controller="Categories" asp-action="Delete" asp-route-id="@category.Id">Удалить</a>
                </div>
            }
            </div>
        </div>
    </div>
</div>}

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/_DraftList.cshtml
@using Microsoft.AspNetCore.Identity;
@using System.Security.Claims;
@using GeekStreamProject.Core.Shared.Entities;

@model IEnumerable<GeekStreamProject.Core.ViewModels.Article.ArticleViewModel>

<div class="d-flex bd-highlight flex-column gap-sm-4">
    @foreach (var article in Model ?? Enumerable.Empty<ArticleViewModel>())
    {
    <div class="d-flex bd-highlight flex-column article-box bg-white gap-3 p-4">
        <div class="d-flex bd-highlight justify-content-between align-items-center">
            <div class="d-flex bd-highlight gap-2">
                <a asp-action="ArticlesByCategory" asp-controller="Categories" asp-route-id="@article.CategoryId"
                   class="d-flex bd-highlight gap-2 text-decoration-none">
                    <div class="image-list">
                        <img class="img-fluid" src="~/@article.CategoryImagePath" />
                    </div>
                    <span class="font-login color-category">
                        @article.CategoryName
                    </span>
                </a>
                <span class="color-datecreation font-content-create">@article.DateOfCreation</span>
            </div>
            <div class="d-flex bd-highlight gap-2 align-items-center">
                <a asp-controller="Account" asp-action="UserProfile" asp-route-userName="@article.AuthorName"
                   class="d-flex bd-highlight gap-2 text-decoration-none">
                    <div class="">
                        <img class="image-list" src="~/@article.AuthorAvatarPath" />
                    </div>
                    <span class="font-login color-name">
                        @article.AuthorName
                    </span>
                </a>
            </div>
        </div>
        <div class="bd-highlight">

            <a asp-controller="Articles" asp-action="CreateArticleFromDraft" asp-route-articleId="@article.Id" class="text-decoration-none" id="title-list-article"><span>@article.Title</span></a>
        </div>
        <div class="bd-highlight box">
            <img src="~/@article.ImagePath" class="mx-auto"  >
        </div>
        <div class="bd-highlight font-article-content-list">
            <span>@article.Description</span>
</div>
        <div class="d-flex bd-highlight justify-content-end">
            <div class="d-flex gap-3 bd-highlight">
                @if (User.Identity.IsAuthenticated && (User.Identity.Name == article.AuthorName || User.FindFirstValue(ClaimTypes.Role) == "Admin"))
                {
                    <div class="bd-highlight">
                        <a asp-controller="Articles" asp-action="Delete" asp-route-id="@article.Id" asp-route-userName="@article.AuthorName" class="btn btn-outline-dark nav-border nav-link nav-font text-decoration-none">Удалить черновик</a>
                    </div>
                }
            </div>
        </div>

    </div>

    }
</div>

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - GeekStreamProject</title>
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/chat.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/profile.css" asp-append-version="true">
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" asp-append-version="true">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Roboto&display=swap" rel="stylesheet">
</head>
<body>
    <header class="border-nav navbar-expand-sm">
        @if (User.Identity.IsAuthenticated)
        {
            await Html.RenderPartialAsync("ExtendedNavBar");
        }
        else
        {
            await Html.RenderPartialAsync("DefaultNavBar");
        }
    </header>
    
<div class="d-flex bd-highligh flex-column">
    <main role="main">
        <div class="">
            @RenderBody()
        </div>
    </main>
</div>


    <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js" asp-append-version="true"></script>



    @await RenderSectionAsync("Scripts", required: false)
    @if (IsSectionDefined("ImageLoad"))
    {
        @await RenderSectionAsync("ImageLoad", required: true)
    }
</body>
</html>

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/_ReviewList.cshtml
@using Microsoft.AspNetCore.Identity;
@using System.Security.Claims;
@using GeekStreamProject.Core.ViewModels.Review;

@model IEnumerable<GeekStreamProject.Core.ViewModels.Review.ReviewArticleViewModel>

<div class="d-flex bd-highlight flex-column gap-sm-4">
    @foreach (var review in Model ?? Enumerable.Empty<ReviewArticleViewModel>())
    {
    <div class="d-flex bd-highlight flex-column article-box bg-white gap-3 p-4">
        <div class="d-flex bd-highlight justify-content-between align-items-center">
            <div class="d-flex bd-highlight gap-2">
                <a asp-action="ArticlesByCategory" asp-controller="Categories" asp-route-id="@review.ArticleViewModel.Id"
                   class="d-flex bd-highlight gap-2 text-decoration-none">
                    <div class="image-list">
                        <img class="img-fluid" src="~/@review.ArticleViewModel.CategoryImagePath" />
                    </div>
                    <span class="font-login color-category">
                        @review.ArticleViewModel.CategoryName
                    </span>
                </a>
                <span class="color-datecreation font-content-create">@review.ArticleViewModel.DateOfCreation</span>
            </div>
            <div class="d-flex bd-highlight gap-2 align-items-center">
                <a asp-controller="Account" asp-action="UserProfile" asp-route-userName="@review.ArticleViewModel.AuthorName"
                   class="d-flex bd-highlight gap-2 text-decoration-none">
                    <div class="">
                        <img class="image-list" src="~/@review.ArticleViewModel.AuthorAvatarPath" />
                    </div>
                    <span class="font-login color-name">
                        @review.ArticleViewModel.AuthorName
                    </span>
                </a>
            </div>
        </div>
        <div class="bd-highlight">
            <a asp-controller="ArticleReviews" asp-action="ReviewArticle" asp-route-id="@review.ArticleViewModel.Id" class="text-decoration-none" id="title-list-article"><span>@review.ArticleViewModel.Title</span></a>
        </div>
        <div class="bd-highlight box">
            <img src="~/@review.ArticleViewModel.ImagePath" class="mx-auto"  >
        </div>
        <div class="bd-highlight font-article-content-list">
            <span>@review.ArticleViewModel.Description</span>
</div>
        <div class="d-flex bd-highlight justify-content-between">
            <div class="d-flex gap-2 bd-highlight">
                <div class="bd-highlight">
                    <img src="~/ImageStorage/Default/Comment.png" />
                </div>
                <div class="bd-highlight font-content" style="color: #828282 !important; font-size: 20px">
                    @review.ArticleViewModel.CommentCount
                </div>
            </div>
            <div class="d-flex gap-3 bd-highlight">
                @if (User.Identity.IsAuthenticated && User.FindFirstValue(ClaimTypes.Role) == "Admin")
                {
                    <div class="bd-highlight">
                        <a asp-controller="Articles" asp-action="Delete" asp-route-id="@review.ArticleViewModel.Id" class="text-decoration-none">Удалить</a>
                    </div>
                }
            </div>
        </div>

    </div>

    }
</div>