GeekStreamProject/src/GeekStreamProject.App/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GeekStreamProject.Core.Abstractions;
using GeekStreamProject.Core.Abstractions.Services;
using GeekStreamProject.Core.ViewModels;
using GeekStreamProject.Core.ViewModels.Article;
using GeekStreamProject.Core.Shared.Entities;
using GeekStreamProject.Core.ViewModels.Comment;
using GeekStreamProject.ENums.ENums;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace GeekStreamProject.App.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ICategoryService _categoryService;
        private readonly ICommentService _commentService;
        private readonly IArticleReviewService _articleReviewService;

        public ArticlesController(IArticleService articleService, ICategoryService categoryService,
            UserManager<ApplicationUser> userManager, ICommentService commentService, IArticleReviewService articleReviewService)
        {
            _articleService = articleService;
            _categoryService = categoryService;
            _userManager = userManager;
            _commentService = commentService;
            _articleReviewService = articleReviewService;
        }

        // GET: Articles
        [HttpGet]
        public async Task<IActionResult> Articles()
        {
            var articleViewModels = await _articleService.GetAllApprovedArticles();

            if (articleViewModels == null)
            {
                return NotFound();
            }

            return View(articleViewModels);
        }

        // GET: Articles/Details/5
        [HttpGet]
        public async Task<IActionResult> DetailArticle(int id)
        {
            var articleViewModels = await _articleService.GetArticle(id);
            if (articleViewModels == null)
            {
                return NotFound();
            }
            ViewBag.Id = id;
            return View(articleViewModels);
        }

        [HttpGet]
        public IActionResult AddNewComment()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View();
            }
            return RedirectToAction("Articles", "Articles");
        }

        [HttpGet]
        public async Task<IActionResult> ChangeRating(int id, int delta)
        {
            await _articleService.ChangeRating(id, delta);
            return RedirectToAction("Articles");
        }

        [HttpPost]
        public async Task<IActionResult> AddNewComment(CreateCommentViewModel createCommentViewModel, bool articleReview = false)
        {
            if (!ModelState.IsValid)
            {
                if (articleReview)
                {
                    return RedirectToAction("ReviewArticle", "ArticleReviews", new { id = createCommentViewModel.ArticleId });
                }
                return RedirectToAction("DetailArticle", new { Id = createCommentViewModel.ArticleId });
            }
            await _commentService.Create(createCommentViewModel);
            if (articleReview)
            {
                return RedirectToAction("ReviewArticle", "ArticleReviews", new { id = createCommentViewModel.ArticleId });
            }
            return RedirectToAction("DetailArticle", new { Id = createCommentViewModel.ArticleId });

        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.Categories = await _categoryService.GetAllCategories();
                return View();
            }
            return RedirectToAction("Articles");
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateArticleViewModel createArticleViewModel, EArticleMode articleMode)
        {
            createArticleViewModel.ArticleMode = articleMode;
            if (!ModelState.IsValid)
            {
                ViewBag.Categories = await _categoryService.GetAllCategories();
                return View(createArticleViewModel);
            }
            int? articleId = await _articleService.Create(createArticleViewModel);
            if (articleId is null)
            {
                return View(createArticleViewModel);
            }

            if (createArticleViewModel.ArticleMode == EArticleMode.UnderReview)
            {
                await _articleReviewService.SendReviewToModerators(articleId);
            }
            
            return RedirectToAction("Articles");
        }

        [HttpGet]
        public async Task<IActionResult> CreateArticleFromDraft(int articleId)
        {
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.Categories = await _categoryService.GetAllCategories();
                var article = await _articleService.GetArticle(articleId);
                CreateArticleViewModel createArticleViewModel = new CreateArticleViewModel()
                {
                    Id = article.Id,
                    Title = article.Title,
                    Content = article.Content,
                    Description = article.Description,
                    CategoryId = article.CategoryId,
                    AuthorId = article.AuthorId
                };
                return View(createArticleViewModel);
            }
            return RedirectToAction("Articles");
        }

        [HttpPost]
        public async Task<IActionResult> CreateArticleFromDraft(CreateArticleViewModel createArticleViewModel, EArticleMode articleMode)
        {
            createArticleViewModel.ArticleMode = articleMode;
            if (!ModelState.IsValid)
            {
                ViewBag.Categories = await _categoryService.GetAllCategories();
                return View(createArticleViewModel);
            }

            await _articleService.DeleteArticle(createArticleViewModel.Id);
            int? articleId = await _articleService.Create(createArticleViewModel);

            if (createArticleViewModel.ArticleMode == EArticleMode.UnderReview)
            {
                await _articleReviewService.SendReviewToModerators(articleId);
            }

            return RedirectToAction("UserProfile", "Account", new {userName = User.Identity.Name});
        }

        [HttpGet]
        public IActionResult ToPublishArticle()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ToPublishArticle(CreatePublishViewModel model)
        {
            await _articleService.ToPublish(model);
            return RedirectToAction("DetailArticle", new { id = model.ArticleId });
        }

        [HttpGet]
        public async Task<IActionResult> AddArticleToDraft(int articleId)
        {
            await _articleService.ToDraft(articleId);
            return RedirectToAction("Articles");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id, string userName)
        {
            await _articleService.DeleteArticle(id);
            return RedirectToAction("UserProfile", "Account", new { userName = userName });
        }

    }
}

GeekStreamProject/src/GeekStreamProject.App/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GeekStreamProject.Core.Abstractions;
using GeekStreamProject.Core.Abstractions.Services;
using GeekStreamProject.Core.ViewModels;
using GeekStreamProject.Core.ViewModels.Article;
using GeekStreamProject.Core.Shared.Entities;
using GeekStreamProject.Core.ViewModels.Comment;
using Microsoft.AspNetCore.Identity;

namespace GeekStreamProject.App.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentService _commentService;

        public CommentController(ICommentService commentService)
        {
            _commentService = commentService;
        }


        [HttpGet]
        public async Task<IActionResult> DeleteComment(int id, int articleId)
        {
            await _commentService.DeleteComment(id);
            return RedirectToAction("DetailArticle", "Articles", new { Id = articleId });
        }

    }
}

GeekStreamProject/src/GeekStreamProject.App/Views/Articles/Articles.cshtml
@{
    ViewData["Title"] = "Статьи";
}


<div class="container">
    <p class="font-header pt-4" style="color:black">Лента</p>
    @await Html.PartialAsync("_ArticleList")
    
</div>

GeekStreamProject/src/GeekStreamProject.App/Views/Articles/Create.cshtml
@using GeekStreamProject.Core.Services;
@using GeekStreamProject.Core.ViewModels.Category
@using System.Linq
@using System.Collections.Immutable
@using GeekStreamProject.ENums.ENums

@using Microsoft.AspNetCore.Http
@model GeekStreamProject.Core.ViewModels.Article.CreateArticleViewModel

@{
    ViewData["Title"] = "Создание статьи";
}

<div class="d-flex flex-column bd-highlight p-4 container" id="CreateArticle">
    <form method="post" enctype="multipart/form-data" asp-action="Create">
        <div class="d-flex bd-highlight gap-2 align-items-center">
            <div class="flex-grow-1 bd-highlight font-header" style="color: #838383 !important;">
                Новая статья
            </div>
            <div class="bd-highlight">
                <input type="submit" value="Сохранить черновик" asp-route-articleMode="@EArticleMode.Draft" class="btn btn-outline-dark nav-border nav-link nav-font" />
            </div>
            <div class="bd-highlight">
                <input type="submit" value="Отправить на рецензирование" asp-route-articleMode="@EArticleMode.UnderReview" class="btn btn-purple nav-font" />
            </div>
        </div>
        <div class="font-content-create" style="color: #212529 !important">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-4">
                <label asp-for="Title" class="form-label">Придумайте название статьи</label>
                <input asp-for="Title" class="form-control" placeholder="Придумайте название статьи" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group mb-4">
                <label asp-for="CategoryId" class="form-label">Выберите категории для статьи</label>
                <select asp-for="CategoryId" class="form-select">
                    <option selected>Выберите категорию...</option>

                    @foreach (CategoryViewModel item in ViewBag.Categories)
                    {
                        <option value="@item.Id">@item.Name</option>
                    }


                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>

            <div class="form-group mb-4">
                <label asp-for="ImageViewModel" class="form-label font-content">Обложка вашей статьи (отображается в ленте)</label>
                <div class="custom-file">
                    <input asp-for="ImageViewModel.File" type="file" class="form-control text-formcontrol border-formcontrol" placeholder="Обложка вашей статьи">
                </div>
                <span asp-validation-for="ImageViewModel" class="text-danger"></span>
            </div>

            <div class="form-group mb-4">
                <label asp-for="Description" class="form-label">Описание статьи (отображается в ленте)</label>
                <textarea asp-for="Description" class="form-control" required rows="3"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group mb-4">
                <label asp-for="Content" class="form-label">Текст статьи</label>
                <textarea asp-for="Content" class="form-control" required rows="15"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GeekStreamProject/src/GeekStreamProject.App/Views/Articles/CreateArticleFromDraft.cshtml
@using GeekStreamProject.Core.Services;
@using GeekStreamProject.ENums.ENums
@using System.Security.Claims;
@model GeekStreamProject.Core.ViewModels.Article.CreateArticleViewModel

<div class="d-flex flex-column bd-highlight p-4 container" id="CreateArticleFromDraft">
    <form method="post" enctype="multipart/form-data" asp-action="CreateArticleFromDraft">
        <div class="d-flex bd-highlight gap-2 align-items-center">
            <div class="flex-grow-1 bd-highlight font-header" style="color: #838383 !important;">
                Черновик
            </div>
            <input asp-for="Id" value="@Model.Id" type="hidden"/>
            <div class="bd-highlight">
                <a asp-action="UserProfile" asp-controller="Account" asp-route-userName="@User.Identity.Name" class="text-decoration-none btn btn-danger nav-border nav-font">Отменить</a>
            </div>
            <div class="bd-highlight">
                <input type="submit" value="Сохранить черновик" asp-route-articleMode="@EArticleMode.Draft" class="btn btn-outline-dark nav-border nav-link nav-font" />
            </div>
            <div class="bd-highlight">
                <input type="submit" value="Отправить на рецензирование" asp-route-articleMode="@EArticleMode.UnderReview" class="btn btn-purple nav-font" />
            </div>
        </div>
        <div class="font-content-create" style="color: #212529 !important">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-4">
                <label asp-for="Title" class="form-label">Придумайте название статьи</label>
                <input asp-for="Title" class="form-control" value="@Model.Title" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group mb-4">
                <label asp-for="CategoryId" class="form-label">Выберите категории для статьи</label>
                <select asp-for="CategoryId" class="form-select">
                    <option selected>Выберите категорию...</option>

                    @foreach (CategoryViewModel item in ViewBag.Categories)
                    {
                        <option value="@item.Id">@item.Name</option>
                    }


                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>

            <div class="form-group mb-4">
                <label asp-for="ImageViewModel" class="form-label font-content">Обложка вашей статьи (отображается в ленте)</label>
                <div class="custom-file">
                    <input asp-for="ImageViewModel.File" type="file" class="form-control text-formcontrol border-formcontrol" placeholder="Обложка вашей статьи">
                </div>
                <span asp-validation-for="ImageViewModel" class="text-danger"></span>
            </div>

            <div class="form-group mb-4">
                <label asp-for="Description" class="form-label">Описание статьи (отображается в ленте)</label>
                <textarea asp-for="Description"  class="form-control" required rows="3">@Model.Description</textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group mb-4">
                <label asp-for="Content" class="form-label">Текст статьи</label>
                <textarea asp-for="Content" class="form-control" required rows="15">@Model.Content</textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
        </div>
    </form>
</div>

GeekStreamProject/src/GeekStreamProject.App/Views/Articles/DetailArticle.cshtml
@using GeekStreamProject.Core.Services;
@using GeekStreamProject.ENums.ENums
@model GeekStreamProject.Core.ViewModels.Article.ArticleViewModel

@{ ViewData["Title"] = "Статья"; }

<div class="d-flex flex-column bd-highlight pt-3 container" id="CreateArticle">
    <div class="d-flex flex-column bd-highlight gap-3 p-3">
        <div class="d-flex bd-highligh justify-content-between gap-3">
            <div class="d-flex bd-highlight gap-2 align-items-center">
                <a asp-action="ArticlesByCategory" asp-controller="Categories" asp-route-id="@Model.CategoryId"
                   class="d-flex bd-highlight gap-2 text-decoration-none" style="color: #4F4F4F">
                    <div class="rounded-2 overflow-hidden bd-highlight" style="width: 24px; height: 24px;">
                        <img class="img-fluid w-100 h-100 d-block" src="~/@Model.CategoryImagePath" />
                    </div>
                    <div class="bd-highlight nav-font">
                        @Model.CategoryName
                    </div>
                </a>
                <div class="bd-highlight font-content">
                    <small style="color: #838383 !important">@Model.DateOfCreation</small>
                </div>
            </div>
            <div class="d-flex bd-highligh align-items-center gap-3">
                @if (Model.AuthorName == User.Identity.Name)
                {
                    <div class="bd-highlight">
                        <a asp-controller="Articles" asp-action="AddArticleToDraft" asp-route-articleId="@Model.Id" class="text-decoration-none btn btn-outline-dark nav-border nav-link nav-fon">Сохранить черновик</a>
                    </div>
                }
                @if (Model.ArticleMode == EArticleMode.InProcessPublished && Model.AuthorName == User.Identity.Name)
                {
                    <div class="bd-highlight">
                        @await Html.PartialAsync("~/Views/Articles/ToPublishArticle.cshtml", Model.publishViewModel)
                    </div>
                }
                @if (Model.ArticleMode == EArticleMode.Published && Model.AuthorName == User.Identity.Name)
                {
                    <div class="bd-highlight">
                        <div class="bd-highlight">
                            <a class="disabled btn btn-purple nav-font">✓ Статья опубликована</a>
                        </div>
                    </div>
                }
            </div>
        </div>

        <div class="bd-highlight font-article-title">
            <span>@Model.Title</span>
        </div>
        <div class="bd-highlight detail">
            <img src="~/@Model.ImagePath" class="mx-auto">
        </div>
        <div class="text-dark bd-highlight font-article-content-list pt-3">
            <span>@Model.Description</span>
        </div>
        <div class="text-dark bd-highlight font-article-content pt-3">
            <span>@Model.Content</span>
        </div>
        <div class="d-flex justify-content-between bd-highlight align-items-center gap-3 pt-3 px-3">
            <div class="d-flex gap-3 bd-highlight justify-content-start">
                <a class="d-flex bd-highlight gap-3 align-items-center text-decoration-none" asp-controller="Account" asp-action="UserProfile" asp-route-userName="@Model.AuthorName">
                    <img src="~/@Model.AuthorAvatarPath" class="nav-image" alt="" />
                    <div class="bd-highlight font-author-name" style="color: #4F4F4F !important;">
                        @Model.AuthorName
                    </div>
                </a>
            </div>

            <div class="d-flex gap-3 bd-highlight">
                <div class="bd-highlight">
                    <img src="~/ImageStorage/Default/DownVector.png" />
                </div>
                <div class="bd-highlight font-content-create" style="color: #219653 !important; font-size: 20px">
                    @Model.Rating
                </div>
                <div class="bd-highlight">
                    <img src="~/ImageStorage/Default/UpVector.png" />
                </div>
            </div>
        </div>
        <div class="bd-highlight font-author-name pt-2" style="color: #383838">
            Ревью (@Model.ReviewComments.Count())
        </div>


        <div class="bd-highlight">
            @await Html.PartialAsync("GetReviewsToArticle", Model)
        </div>
        <div class="bd-highlight font-author-name pt-2" style="color: #383838">
            Комментарии (@Model.CommentCount)
        </div>


        <div class="bd-highlight">
            @await Html.PartialAsync("GetCommentsToArticle", Model)
        </div>

    </div>
    </div>

GeekStreamProject/src/GeekStreamProject.App/Views/Articles/GetCommentsToArticle.cshtml
@using GeekStreamProject.ENums.ENums
@model GeekStreamProject.Core.ViewModels.Article.ArticleViewModel
<input type="hidden" value=@using System.Security.Claims />
<div class="d-flex flex-column bd-highlight gap-3">
    @{
        var count = 0;
    }
    @foreach (var comment in Model.Comments)
    {
        count++;
        <div class="d-flex flex-column bd-highlight gap-2 card px-3 py-2">
            @if (comment.ParentCommentContent != null)
            {
                <p><small>Ответ на: @comment.ParentCommentContent</small></p>
            }
            <div class="d-flex gap-2 bd-highlight justify-content-start align-items-center text-decoration-none">
                <a class="d-flex bd-highlight gap-2 align-items-center text-decoration-noned-flex bd-highlight gap-2 align-items-center text-decoration-none"
                   asp-controller="Account" asp-action="UserProfile" asp-route-id="@comment.CommentatorName" asp-route-userName="@comment.CommentatorName">
                    <img src="~/@comment.CommentatorAvatarUrl" class="bd-highlight comment-image " alt="" />
                    <div class="bd-highlight nav-font" style="color: #383838 !important;">
                        @comment.CommentatorName
                    </div>
                </a>
                <small class="bd-highlight font-content" style="color: #838383 !important">@comment.DateOfCreation</small>
            </div>

            <div class="bd-highlight font-inter-500">
                <span style="word-wrap: break-word;">@comment.Content</span>
            </div>

            <div class="d-flex justify-content-between bd-highlight align-items-center">
                <div class="bd-highlight">
                    <a class="bd-highlight text-decoration-none font-author-name" style="font-size: 16px !important; color: #4F4F4F !important"
                       href="#AddComment" data-bs-toggle="collapse" role="button" aria-expanded="false" aria-controls="collapseExample">
                        Ответить
                    </a>
                    <div class="collapse" id="AddComment">
                        <div class="bd-highlight px-3 pt-2">
                            @if (User.Identity.IsAuthenticated)
                            {
                                comment.CreateViewModel = new() { ArticleId = comment.ArticleId, ParentCommentId = comment.Id };
                                await Html.RenderPartialAsync("~/Views/Comments/AddNewComment.cshtml", comment.CreateViewModel);
                            }
                        </div>
                    </div>
                </div>


                <div class="d-flex gap-3 bd-highlight">
                    @if (Model.ArticleMode != EArticleMode.UnderReview)
                    {
                        @if (User.Identity.IsAuthenticated && (User.FindFirstValue(ClaimTypes.Role) == "Admin" || User.FindFirstValue(ClaimTypes.Role) == "Moderator"))
                        {
                            <div class="d-flex bd-highlight">
                                <a class=" bd-highlight text-decoration-none font-author-name" asp-controller="Comment"
                                   asp-action="DeleteComment" asp-route-id="@comment.Id" asp-route-articleId="@comment.ArticleId" style="font-size: 16px; color: #4F4F4F !important">
                                    Удалить
                                </a>
                            </div>
                        }
                    }

                    <div class="bd-highlight">
                        <img src="~/ImageStorage/Default/DownVector.png" />
                    </div>
                    <div class="bd-highlight font-content-create" style="color: #219653 !important; font-size: 20px">
                        @comment.Rating
                    </div>
                    <div class="bd-highlight">
                        <img src="~/ImageStorage/Default/UpVector.png" />
                    </div>
                </div>
            </div>
        </div>
    }
    @if (User.Identity.IsAuthenticated && Model.ArticleMode == EArticleMode.Published)
    {
        <div class="bd-highlight pt-2">
            @{
                Model.CreateCommentViewModel.ParentCommentId = null;
            }
            @await Html.PartialAsync("~/Views/Comments/AddNewComment.cshtml", Model.CreateCommentViewModel)
        </div>
    }
    else if (!User.Identity.IsAuthenticated)
    {
        <div class="alert alert-warning bd-highlight pt-2" role="alert">
            Вы не авторизованы для написания комментария!
        </div>
    }
    else if (User.Identity.IsAuthenticated && (Model.ArticleMode == EArticleMode.UnderReview || Model.ArticleMode == EArticleMode.InProcessPublished) && User.IsInRole("Moderator"))
    {
<div class="bd-highlight pt-2">
    @{
        Model.CreateCommentViewModel.ParentCommentId = null;
    }
    @await Html.PartialAsync("~/Views/Comments/AddNewComment.cshtml", Model.CreateCommentViewModel)
</div>
    }
</div>

GeekStreamProject/src/GeekStreamProject.App/Views/Articles/GetReviewsToArticle.cshtml
@using GeekStreamProject.ENums.ENums
@model GeekStreamProject.Core.ViewModels.Article.ArticleViewModel
<input type="hidden" value=@using System.Security.Claims />
<div class="d-flex flex-column bd-highlight gap-3">
    @{
        var count = 0;
    }
    @foreach (var comment in Model.ReviewComments)
    {
        count++;
        <div class="d-flex flex-column bd-highlight gap-2 card px-3 py-2">
            @if (comment.ParentCommentContent != null)
            {
                <p><small>Ответ на: @comment.ParentCommentContent</small></p>
            }
            <div class="d-flex gap-2 bd-highlight justify-content-start align-items-center text-decoration-none">
                <a class="d-flex bd-highlight gap-2 align-items-center text-decoration-noned-flex bd-highlight gap-2 align-items-center text-decoration-none"
                   asp-controller="Account" asp-action="UserProfile" asp-route-id="@comment.CommentatorName" asp-route-userName="@comment.CommentatorName">
                    <img src="~/@comment.CommentatorAvatarUrl" class="bd-highlight comment-image " alt="" />
                    <div class="bd-highlight nav-font" style="color: #383838 !important;">
                        @comment.CommentatorName
                    </div>
                </a>
                <small class="bd-highlight font-content" style="color: #838383 !important">@comment.DateOfCreation</small>
            </div>

            <div class="bd-highlight font-inter-500">
                <span style="word-wrap: break-word;">@comment.Content</span>
            </div>

            <div class="d-flex justify-content-between bd-highlight align-items-center">

                <div class="d-flex gap-3 bd-highlight">
                    @if (Model.ArticleMode != EArticleMode.UnderReview)
                    {
                        @if (User.Identity.IsAuthenticated && (User.FindFirstValue(ClaimTypes.Role) == "Admin"))
                        {
                            <div class="d-flex bd-highlight">
                                <a class=" bd-highlight text-decoration-none font-author-name" asp-controller="Comment"
                                   asp-action="DeleteComment" asp-route-id="@comment.Id" asp-route-articleId="@comment.ArticleId" style="font-size: 16px; color: #4F4F4F !important">
                                    Удалить
                                </a>
                            </div>
                        }
                    }

                    <div class="bd-highlight">
                        <img src="~/ImageStorage/Default/DownVector.png" />
                    </div>
                    <div class="bd-highlight font-content-create" style="color: #219653 !important; font-size: 20px">
                        @comment.Rating
                    </div>
                    <div class="bd-highlight">
                        <img src="~/ImageStorage/Default/UpVector.png" />
                    </div>
                </div>
            </div>
        </div>
    }
</div>

GeekStreamProject/src/GeekStreamProject.App/Views/Articles/ToPublishArticle.cshtml
@using System.Security.Claims;
@using GeekStreamProject.ENums.ENums;
@model GeekStreamProject.Core.ViewModels.Article.CreatePublishViewModel


    <div class="" id="CreateApprove">
        <form asp-action="ToPublishArticle" asp-controller="Articles" asp-route-id="@Model.ArticleId" method="post">
            <input asp-for="ArticleMode" type="hidden" value="@EArticleMode.Published" />
            <input asp-for="ArticleId" type="hidden" value="@Model.ArticleId" />

            <div class="bd-highlight">
                <input type="submit" value="Опубликовать" class="btn btn-purple nav-font" />
            </div>
        </form>
    </div>